@startuml

note "Layered Architecture" as N1

component ClinicSystem {
    top to bottom direction

    component ClinicUserInterface
    component ClinicBusinessLogic
    component Infrastructure
    component ExternalServiceProxyManager
    database RDBMS

    HTTPS -- ClinicBusinessLogic
    ClinicUserInterface --( HTTPS

    Infrastructure <--> RDBMS
    Infrastructure <--> ExternalServiceProxyManager
    ClinicBusinessLogic --> Infrastructure
}



@enduml